name: Scraper
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Enables manual trigger
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'
        type: string

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Set up Python
        run: uv python install 3.13
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        
      - name: Install dependencies
        run: uv sync
        
      - name: Run script with headless Chrome
        run: uv run python main.py
        env:
          DISPLAY: :99  # For headless mode
