name: Python Script with Chrome - Store Results
on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Manual trigger
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing commits
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          
      - name: Set up Python with uv
        run: uv python install 3.13
        
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          
      - name: Install dependencies
        run: uv sync
        
      - name: Debug environment
        run: |
          echo "=== System Information ==="
          uname -a
          echo "=== Chrome and ChromeDriver ==="
          google-chrome --version
          which google-chrome
          echo "=== Environment Variables ==="
          env | grep -E "(DISPLAY|CHROME|PATH)" | sort
          echo "=== Network Test ==="
          curl -I https://google.com || echo "Network test failed"
        
      - name: Run Python script with debug
        run: uv run python main.py
        
      - name: Commit and push results
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add timestamp to commit message
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S UTC')
          
          # Add results directory
          git add results/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "[data] update results: $TIMESTAMP

            Run triggered by: ${{ github.event_name }}
            ${{ github.event_name == 'workflow_dispatch' && format('Reason: {0}', inputs.reason) || '' }}"
            
            git push
            echo "Results committed and pushed successfully"
          fi
        
      - name: Print summary
        run: |
          echo "## Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp:** $(date '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "- **Trigger:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "- **Reason:** ${{ inputs.reason }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **Results stored in:** \`results/\` directory" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifacts:** Available for 30 days" >> $GITHUB_STEP_SUMMARY
          
          # List files in results directory
          if [ -d "results" ] && [ "$(ls -A results)" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Generated Files:" >> $GITHUB_STEP_SUMMARY
            ls -la results/ | tail -n +2 | while read line; do
              echo "- \`$line\`" >> $GITHUB_STEP_SUMMARY
            done
          fi